# Generated by Django 6.0.5 on 2026-05-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
