# Generated by Django 6.0.5 on 2026-05-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_media_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='poster_position_x',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='media',
            name='poster_position_y',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
