# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0003_media_poster_position_x_media_poster_position_y"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="backdrop",
            field=models.FileField(blank=True, null=True, upload_to="backdrops/"),
        ),
    ]
